---
apiVersion: v1
kind: Service
metadata:
  name: mytest-service
  labels:
    app: mytest
spec:
  type: NodePort
  selector:
    app: mytest
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytest-deployment
spec:
  selector:
    matchLabels:
      app: mytest
  replicas: 3
  template:
    metadata:
      labels:
        app: mytest
    spec:
      containers:
      - name: mytest
        image: amoolekan/mytest:latest
        ports:
        - containerPort: 8080
